### ISSUE TITLE
Not loading asset which uploaded to poly 

### ISSUE THREAD

**Issue by raghu462** [googlevr/poly-sample-android#3]
I have uploaded.obj file to poly website and it's public. i am able to get the response from poly API but not rendering in ARCore sample app.

**Comment by btco** [comment]
Can you give a link to the asset you uploaded?

Note: the renderer for the ARCore sample only supports models with a single texture. If your model is using more than one texture, it won't work.

**Comment by raghu462** [comment]
thanks, I have uploaded a model with multi textures so will try with a single texture and let you know.

**Comment by btco** [comment]
Please reopen if you still notice the problem when using a model with a single texture. Thanks!
