### ISSUE TITLE
Poly Sample Android app only seems to be able to load `5vbJ5vildOq` piano 3d model.

### ISSUE THREAD

**Issue by kanawish** [googlevr/poly-sample-android#4]
I've been playing around with the poly-sample-android app, and I have yet to find a single "Blocks" model beyond the Piano that loads correctly.

Examples :
`private static final String ASSET_ID = "bvLXsDt9mww";`
![image](https://user-images.githubusercontent.com/1449618/33800704-c688ff5e-dd13-11e7-99f5-f3cf738ef33d.png)

`private static final String ASSET_ID = "33q9hiqgpjI";`
![image](https://user-images.githubusercontent.com/1449618/33800705-cec42d7e-dd13-11e7-97f1-5c245ae0ae9b.png)

`private static final String ASSET_ID = "4vlKrz5wDOF";`
![image](https://user-images.githubusercontent.com/1449618/33800706-d1f82d2e-dd13-11e7-9316-39ea1a37addb.png)

`private static final String ASSET_ID = "cKGOC6jRWoQ";`
![image](https://user-images.githubusercontent.com/1449618/33800707-d4ad1b4c-dd13-11e7-93e9-9bd4fc65cb81.png)

`private static final String ASSET_ID = "bI22sEdka83";`
![image](https://user-images.githubusercontent.com/1449618/33800708-d80721e8-dd13-11e7-82f8-88ee35948198.png)

`private static final String ASSET_ID = "2E1zBn09bQm";`
![image](https://user-images.githubusercontent.com/1449618/33800709-d9ebfb5a-dd13-11e7-9ab7-bcb7be84f61e.png)

Even the other Blocks samples by the same author as "Piano" display with similar looking distortion.

**Comment by btco** [comment]
Thanks for reporting! We'll look into it!

**Comment by btco** [comment]
I found out what's going on. A silly error in our parsing code. I'll commit a fix soon.

**Comment by btco** [comment]
Fixed. Thank you for reporting.

**Comment by wangjiangchuan** [comment]
I have also found the bug and debuged it. Yes, the parse function seems to have a problem in scale&translate function, which will change to the vertex position several time.
